import { NLUResult, Intent } from "./intents";
import { levenshtein } from "../utils/levenshtein";

interface FuzzyCandidate {
  phrase: string;
  intent: Intent;
  confidence: number;
  entities?: Record<string, any>;
  extract?: (words: string[]) => Record<string, any>;
}

const FUZZY_COMMANDS: FuzzyCandidate[] = [
  // ── Quick FR ──
  { phrase: "annule", intent: Intent.Undo, confidence: 0.85 },
  { phrase: "refais", intent: Intent.Redo, confidence: 0.85 },
  { phrase: "sauvegarde", intent: Intent.Save, confidence: 0.85 },
  { phrase: "copie", intent: Intent.Copy, confidence: 0.85 },
  { phrase: "colle", intent: Intent.Paste, confidence: 0.85 },
  { phrase: "coupe", intent: Intent.Cut, confidence: 0.85 },
  { phrase: "supprime ligne", intent: Intent.DeleteLine, confidence: 0.80 },
  { phrase: "duplique ligne", intent: Intent.DuplicateLine, confidence: 0.80 },
  { phrase: "selectionne tout", intent: Intent.SelectAll, confidence: 0.80 },
  { phrase: "selectionne ligne", intent: Intent.SelectLine, confidence: 0.80 },
  { phrase: "selectionne mot", intent: Intent.SelectWord, confidence: 0.80 },
  { phrase: "indente", intent: Intent.Indent, confidence: 0.85 },
  { phrase: "nouvelle ligne en dessous", intent: Intent.NewLineBelow, confidence: 0.75 },
  { phrase: "nouvelle ligne au dessus", intent: Intent.NewLineAbove, confidence: 0.75 },
  { phrase: "ferme l'onglet", intent: Intent.CloseTab, confidence: 0.80 },
  { phrase: "nouveau fichier", intent: Intent.NewFile, confidence: 0.80 },
  { phrase: "ouvre le terminal", intent: Intent.OpenTerminal, confidence: 0.80 },
  { phrase: "lance les tests", intent: Intent.RunCommand, confidence: 0.80, extract: () => ({ command: "test" }) },
  { phrase: "compile", intent: Intent.RunCommand, confidence: 0.85, extract: () => ({ command: "build" }) },
  { phrase: "formate", intent: Intent.FormatDocument, confidence: 0.85 },
  { phrase: "va au debut", intent: Intent.GoToStart, confidence: 0.80 },
  { phrase: "va a la fin", intent: Intent.GoToEnd, confidence: 0.80 },
  { phrase: "monte", intent: Intent.MoveUp, confidence: 0.85 },
  { phrase: "descend", intent: Intent.MoveDown, confidence: 0.85 },
  { phrase: "gauche", intent: Intent.MoveLeft, confidence: 0.85 },
  { phrase: "droite", intent: Intent.MoveRight, confidence: 0.85 },

  // ── FR: New commands ──
  { phrase: "defile haut", intent: Intent.ScrollUp, confidence: 0.80 },
  { phrase: "defile bas", intent: Intent.ScrollDown, confidence: 0.80 },
  { phrase: "page haut", intent: Intent.PageUp, confidence: 0.80 },
  { phrase: "page bas", intent: Intent.PageDown, confidence: 0.80 },
  { phrase: "va au mot gauche", intent: Intent.MoveWordLeft, confidence: 0.78 },
  { phrase: "va au mot droite", intent: Intent.MoveWordRight, confidence: 0.78 },
  { phrase: "va a la definition", intent: Intent.GoToDefinition, confidence: 0.78 },
  { phrase: "va aux references", intent: Intent.GoToReferences, confidence: 0.78 },
  { phrase: "commente la ligne", intent: Intent.ToggleComment, confidence: 0.80 },
  { phrase: "commente en bloc", intent: Intent.ToggleBlockComment, confidence: 0.78 },
  { phrase: "plie", intent: Intent.Fold, confidence: 0.85 },
  { phrase: "deplie", intent: Intent.Unfold, confidence: 0.85 },
  { phrase: "plie tout", intent: Intent.FoldAll, confidence: 0.80 },
  { phrase: "deplie tout", intent: Intent.UnfoldAll, confidence: 0.80 },
  { phrase: "ferme tout", intent: Intent.CloseAllTabs, confidence: 0.80 },
  { phrase: "reouvre l'onglet", intent: Intent.ReopenClosedTab, confidence: 0.78 },
  { phrase: "divise l'editeur", intent: Intent.SplitEditor, confidence: 0.78 },
  { phrase: "supprime le mot", intent: Intent.DeleteWord, confidence: 0.80 },
  { phrase: "deplace ligne haut", intent: Intent.MoveLineUp, confidence: 0.78 },
  { phrase: "deplace ligne bas", intent: Intent.MoveLineDown, confidence: 0.78 },
  { phrase: "joindre lignes", intent: Intent.JoinLines, confidence: 0.78 },
  { phrase: "trier lignes", intent: Intent.SortLines, confidence: 0.78 },
  { phrase: "cherche suivant", intent: Intent.FindNext, confidence: 0.80 },
  { phrase: "remplace tout", intent: Intent.ReplaceAll, confidence: 0.80 },
  { phrase: "ferme la recherche", intent: Intent.CloseSearch, confidence: 0.78 },
  { phrase: "suivant", intent: Intent.NextTab, confidence: 0.85 },
  { phrase: "precedent", intent: Intent.PreviousTab, confidence: 0.85 },
  { phrase: "efface terminal", intent: Intent.ClearTerminal, confidence: 0.80 },
  { phrase: "focus terminal", intent: Intent.FocusTerminal, confidence: 0.80 },
  { phrase: "montre barre laterale", intent: Intent.ToggleSidebar, confidence: 0.78 },
  { phrase: "montre le panneau", intent: Intent.TogglePanel, confidence: 0.78 },
  { phrase: "explorateur", intent: Intent.ToggleExplorer, confidence: 0.80 },
  { phrase: "parametres", intent: Intent.OpenSettings, confidence: 0.80 },
  { phrase: "extensions", intent: Intent.OpenExtensions, confidence: 0.80 },
  { phrase: "zoom", intent: Intent.ZoomIn, confidence: 0.85 },
  { phrase: "dezoom", intent: Intent.ZoomOut, confidence: 0.85 },
  { phrase: "git commit", intent: Intent.GitCommit, confidence: 0.85 },
  { phrase: "git push", intent: Intent.GitPush, confidence: 0.85 },
  { phrase: "git pull", intent: Intent.GitPull, confidence: 0.85 },
  { phrase: "git statut", intent: Intent.GitStatus, confidence: 0.85 },
  { phrase: "git diff", intent: Intent.GitDiff, confidence: 0.85 },
  { phrase: "git journal", intent: Intent.GitLog, confidence: 0.85 },
  { phrase: "demarre le debug", intent: Intent.StartDebugging, confidence: 0.80 },
  { phrase: "arrete le debug", intent: Intent.StopDebugging, confidence: 0.80 },
  { phrase: "palier dessus", intent: Intent.StepOver, confidence: 0.80 },
  { phrase: "palier dessous", intent: Intent.StepInto, confidence: 0.80 },
  { phrase: "palier sortir", intent: Intent.StepOut, confidence: 0.80 },
  { phrase: "continue", intent: Intent.ContinueDebugging, confidence: 0.80 },
  { phrase: "ajoute breakpoint", intent: Intent.ToggleBreakpoint, confidence: 0.78 },
  { phrase: "renomme le symbole", intent: Intent.RenameSymbol, confidence: 0.78 },
  { phrase: "correction rapide", intent: Intent.QuickFix, confidence: 0.80 },
  { phrase: "refactorise", intent: Intent.RefactorAction, confidence: 0.80 },
  { phrase: "apercu definition", intent: Intent.PeekDefinition, confidence: 0.78 },
  { phrase: "ajoute signet", intent: Intent.ToggleBookmark, confidence: 0.78 },
  { phrase: "signet suivant", intent: Intent.NextBookmark, confidence: 0.78 },
  { phrase: "ajoute curseur dessus", intent: Intent.AddCursorAbove, confidence: 0.75 },
  { phrase: "ajoute curseur dessous", intent: Intent.AddCursorBelow, confidence: 0.75 },
  { phrase: "selectionne suivante", intent: Intent.SelectNextOccurrence, confidence: 0.78 },
  { phrase: "nouvelle fenetre", intent: Intent.NewWindow, confidence: 0.80 },
  { phrase: "ferme la fenetre", intent: Intent.CloseWindow, confidence: 0.80 },
  { phrase: "sauve tout", intent: Intent.SaveAll, confidence: 0.80 },
  { phrase: "ferme tout les editeurs", intent: Intent.CloseAllEditors, confidence: 0.78 },
  { phrase: "prochain editeur", intent: Intent.NextEditor, confidence: 0.78 },
  { phrase: "editeur precedent", intent: Intent.PreviousEditor, confidence: 0.78 },

  // ── Quick EN ──
  { phrase: "undo", intent: Intent.Undo, confidence: 0.85 },
  { phrase: "redo", intent: Intent.Redo, confidence: 0.85 },
  { phrase: "save", intent: Intent.Save, confidence: 0.85 },
  { phrase: "copy", intent: Intent.Copy, confidence: 0.85 },
  { phrase: "paste", intent: Intent.Paste, confidence: 0.85 },
  { phrase: "cut", intent: Intent.Cut, confidence: 0.85 },
  { phrase: "delete line", intent: Intent.DeleteLine, confidence: 0.80 },
  { phrase: "duplicate line", intent: Intent.DuplicateLine, confidence: 0.80 },
  { phrase: "select all", intent: Intent.SelectAll, confidence: 0.80 },
  { phrase: "select line", intent: Intent.SelectLine, confidence: 0.80 },
  { phrase: "select word", intent: Intent.SelectWord, confidence: 0.80 },
  { phrase: "indent", intent: Intent.Indent, confidence: 0.85 },
  { phrase: "new line below", intent: Intent.NewLineBelow, confidence: 0.80 },
  { phrase: "new line above", intent: Intent.NewLineAbove, confidence: 0.80 },
  { phrase: "close tab", intent: Intent.CloseTab, confidence: 0.80 },
  { phrase: "new file", intent: Intent.NewFile, confidence: 0.80 },
  { phrase: "open terminal", intent: Intent.OpenTerminal, confidence: 0.80 },
  { phrase: "run tests", intent: Intent.RunCommand, confidence: 0.80, extract: () => ({ command: "test" }) },
  { phrase: "build", intent: Intent.RunCommand, confidence: 0.85, extract: () => ({ command: "build" }) },
  { phrase: "format", intent: Intent.FormatDocument, confidence: 0.85 },
  { phrase: "go to start", intent: Intent.GoToStart, confidence: 0.80 },
  { phrase: "go to end", intent: Intent.GoToEnd, confidence: 0.80 },
  { phrase: "go up", intent: Intent.MoveUp, confidence: 0.85 },
  { phrase: "go down", intent: Intent.MoveDown, confidence: 0.85 },
  { phrase: "go left", intent: Intent.MoveLeft, confidence: 0.85 },
  { phrase: "go right", intent: Intent.MoveRight, confidence: 0.85 },

  // ── EN: New commands ──
  { phrase: "scroll up", intent: Intent.ScrollUp, confidence: 0.80 },
  { phrase: "scroll down", intent: Intent.ScrollDown, confidence: 0.80 },
  { phrase: "page up", intent: Intent.PageUp, confidence: 0.80 },
  { phrase: "page down", intent: Intent.PageDown, confidence: 0.80 },
  { phrase: "move word left", intent: Intent.MoveWordLeft, confidence: 0.78 },
  { phrase: "move word right", intent: Intent.MoveWordRight, confidence: 0.78 },
  { phrase: "go to definition", intent: Intent.GoToDefinition, confidence: 0.78 },
  { phrase: "go to references", intent: Intent.GoToReferences, confidence: 0.78 },
  { phrase: "toggle comment", intent: Intent.ToggleComment, confidence: 0.80 },
  { phrase: "block comment", intent: Intent.ToggleBlockComment, confidence: 0.78 },
  { phrase: "fold", intent: Intent.Fold, confidence: 0.85 },
  { phrase: "unfold", intent: Intent.Unfold, confidence: 0.85 },
  { phrase: "fold all", intent: Intent.FoldAll, confidence: 0.80 },
  { phrase: "unfold all", intent: Intent.UnfoldAll, confidence: 0.80 },
  { phrase: "close all", intent: Intent.CloseAllTabs, confidence: 0.80 },
  { phrase: "reopen tab", intent: Intent.ReopenClosedTab, confidence: 0.78 },
  { phrase: "split editor", intent: Intent.SplitEditor, confidence: 0.78 },
  { phrase: "delete word", intent: Intent.DeleteWord, confidence: 0.80 },
  { phrase: "move line up", intent: Intent.MoveLineUp, confidence: 0.78 },
  { phrase: "move line down", intent: Intent.MoveLineDown, confidence: 0.78 },
  { phrase: "join lines", intent: Intent.JoinLines, confidence: 0.78 },
  { phrase: "sort lines", intent: Intent.SortLines, confidence: 0.78 },
  { phrase: "find next", intent: Intent.FindNext, confidence: 0.80 },
  { phrase: "replace all", intent: Intent.ReplaceAll, confidence: 0.80 },
  { phrase: "close search", intent: Intent.CloseSearch, confidence: 0.78 },
  { phrase: "next tab", intent: Intent.NextTab, confidence: 0.85 },
  { phrase: "previous tab", intent: Intent.PreviousTab, confidence: 0.85 },
  { phrase: "clear terminal", intent: Intent.ClearTerminal, confidence: 0.80 },
  { phrase: "focus terminal", intent: Intent.FocusTerminal, confidence: 0.80 },
  { phrase: "toggle sidebar", intent: Intent.ToggleSidebar, confidence: 0.78 },
  { phrase: "toggle panel", intent: Intent.TogglePanel, confidence: 0.78 },
  { phrase: "explorer", intent: Intent.ToggleExplorer, confidence: 0.80 },
  { phrase: "settings", intent: Intent.OpenSettings, confidence: 0.80 },
  { phrase: "extensions", intent: Intent.OpenExtensions, confidence: 0.80 },
  { phrase: "zoom in", intent: Intent.ZoomIn, confidence: 0.85 },
  { phrase: "zoom out", intent: Intent.ZoomOut, confidence: 0.85 },
  { phrase: "git commit", intent: Intent.GitCommit, confidence: 0.85 },
  { phrase: "git push", intent: Intent.GitPush, confidence: 0.85 },
  { phrase: "git pull", intent: Intent.GitPull, confidence: 0.85 },
  { phrase: "git status", intent: Intent.GitStatus, confidence: 0.85 },
  { phrase: "git diff", intent: Intent.GitDiff, confidence: 0.85 },
  { phrase: "git log", intent: Intent.GitLog, confidence: 0.85 },
  { phrase: "start debugging", intent: Intent.StartDebugging, confidence: 0.80 },
  { phrase: "stop debugging", intent: Intent.StopDebugging, confidence: 0.80 },
  { phrase: "step over", intent: Intent.StepOver, confidence: 0.80 },
  { phrase: "step into", intent: Intent.StepInto, confidence: 0.80 },
  { phrase: "step out", intent: Intent.StepOut, confidence: 0.80 },
  { phrase: "toggle breakpoint", intent: Intent.ToggleBreakpoint, confidence: 0.78 },
  { phrase: "rename symbol", intent: Intent.RenameSymbol, confidence: 0.78 },
  { phrase: "quick fix", intent: Intent.QuickFix, confidence: 0.80 },
  { phrase: "refactor", intent: Intent.RefactorAction, confidence: 0.80 },
  { phrase: "peek definition", intent: Intent.PeekDefinition, confidence: 0.78 },
  { phrase: "add bookmark", intent: Intent.ToggleBookmark, confidence: 0.78 },
  { phrase: "next bookmark", intent: Intent.NextBookmark, confidence: 0.78 },
  { phrase: "add cursor above", intent: Intent.AddCursorAbove, confidence: 0.75 },
  { phrase: "add cursor below", intent: Intent.AddCursorBelow, confidence: 0.75 },
  { phrase: "select next occurrence", intent: Intent.SelectNextOccurrence, confidence: 0.78 },
  { phrase: "new window", intent: Intent.NewWindow, confidence: 0.80 },
  { phrase: "close window", intent: Intent.CloseWindow, confidence: 0.80 },
  { phrase: "save all", intent: Intent.SaveAll, confidence: 0.80 },
  { phrase: "close all editors", intent: Intent.CloseAllEditors, confidence: 0.78 },
  { phrase: "next editor", intent: Intent.NextEditor, confidence: 0.78 },
  { phrase: "previous editor", intent: Intent.PreviousEditor, confidence: 0.78 },
  { phrase: "uppercase", intent: Intent.Uppercase, confidence: 0.80 },
  { phrase: "lowercase", intent: Intent.Lowercase, confidence: 0.80 },
  { phrase: "trim whitespace", intent: Intent.TrimWhitespace, confidence: 0.78 },
  { phrase: "pin tab", intent: Intent.PinTab, confidence: 0.80 },

  // ── Dictation FR ──
  { phrase: "dicte", intent: Intent.DictateToggle, confidence: 0.85 },
  { phrase: "mode dictee", intent: Intent.DictateToggle, confidence: 0.80 },
  { phrase: "arrete la dictee", intent: Intent.DictateToggle, confidence: 0.80 },
  { phrase: "arrete dicte", intent: Intent.DictateToggle, confidence: 0.80 },

  // ── Dictation EN ──
  { phrase: "dictate", intent: Intent.DictateToggle, confidence: 0.85 },
  { phrase: "dictation mode", intent: Intent.DictateToggle, confidence: 0.80 },
  { phrase: "stop dictation", intent: Intent.DictateToggle, confidence: 0.80 },
];

const MAX_EDIT_DISTANCE = 3;

export function fuzzyMatch(text: string): NLUResult | null {
  let bestMatch: { result: NLUResult; distance: number } | null = null;

  for (const cmd of FUZZY_COMMANDS) {
    const distance = levenshtein(text, cmd.phrase);
    if (distance <= MAX_EDIT_DISTANCE) {
      if (!bestMatch || distance < bestMatch.distance) {
        const entities = cmd.extract ? cmd.extract(text.split(" ")) : {};
        bestMatch = {
          result: {
            intent: cmd.intent,
            confidence: cmd.confidence,
            entities,
            rawText: text,
          },
          distance,
        };
      }
    }
  }

  return bestMatch?.result ?? null;
}
